# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('cell', models.CharField(default='', max_length=11, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField(max_length=100)),
                ('loan_begin', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_rate', models.DecimalField(decimal_places=3, default=0.03, max_digits=5)),
                ('loan_period', models.IntegerField(default=30)),
                ('loan_model', models.CharField(choices=[('BI', 'Before_Interest'), ('EP', 'Equal_Principal')], default='BI', max_length=2)),
                ('client_mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Client')),
            ],
            options={
                'ordering': ('loan_end',),
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.CharField(blank=True, default='', max_length=100)),
                ('sms_status', models.CharField(choices=[('True', 'The sms is sent'), ('False', 'Sent failed')], default='False', max_length=5)),
                ('client_sms_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Client')),
            ],
        ),
    ]
