# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20171111_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='account_client',
            new_name='account_customer',
        ),
    ]
