# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20171111_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='customer_mortgage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
