# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20171112_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortgage',
            name='loan_period',
        ),
    ]
